name: Backend CI/CD

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'bookBazaar/**'
      - '.github/workflows/backend.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'bookBazaar/**'

jobs:
  build:
    name: Build Backend
    #needs: test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./bookBazaar
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    
    - name: Build application
      run: ./gradlew build -x test
    
    - name: Build Docker image
      if: github.ref == 'refs/heads/main'
      run: ./gradlew bootBuildImage --imageName=book-bazaar-backend:latest
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: backend-artifacts
        path: |
          bookBazaar/build/libs/*.jar
          bookBazaar/build/distributions/*

  testing:
    name: Test Backend
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./bookBazaar/bookBazaar
    steps:
      - name: Run tests
        run: ./gradlew test
      - name: Stop tests
        run: ./gradlew test